import type { Metadata } from 'next'
import { Poor_Story } from 'next/font/google'
import './globals.css'

const poorStory = Poor_Story({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="stylesheet" as="style" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.min.css" />
      <body className={poorStory.className}>{children}</body>
    </html>
  )
}
